<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('activities')->insert([
            [
                'name' => 'Visita a la Alcazaba de Almería',
                'description' => 'Explora la impresionante fortaleza árabe con vistas panorámicas de la ciudad y el mar Mediterráneo.',
                'photo' => 'alcazaba_almeria.jpg',
                'type' => 'Monumentos',
                'place_id' => 1,
                'price' => 10.00,
                'address' => 'Calle Almanzor, s/n, 04002',
                'latitude' => 36.8402,
                'longitude' => -2.4717,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Visita a la Alhambra y los Jardines del Generalife',
                'description' => 'Sumérgete en la historia y la arquitectura islámica de este impresionante palacio y sus jardines.',
                'photo' => 'alhambra_granada.jpg',
                'type' => 'Monumentos',
                'place_id' => 2,
                'price' => 15.00,
                'address' => 'Calle Real de la Alhambra, s/n, 18009',
                'latitude' => 37.1775,
                'longitude' => -3.5875,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tour por la Sagrada Familia',
                'description' => 'Descubre la obra maestra inacabada de Antoni Gaudí y aprende sobre su arquitectura única.',
                'photo' => 'sagrada_familia.jpg',
                'type' => 'Turismo',
                'place_id' => 3,
                'price' => 12.50,
                'address' => 'Carrer de Mallorca, 401, 08013',
                'latitude' => 41.4036,
                'longitude' => 2.1744,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Visita al Anfiteatro Romano de Tarragona',
                'description' => 'Explora uno de los mejores ejemplos de arquitectura romana en España, situado frente al mar Mediterráneo.',
                'photo' => 'anfiteatro_tarragona.jpg',
                'type' => 'Monumentos',
                'place_id' => 4,
                'price' => 8.75,
                'address' => 'Carrer de les Monges, 25, 43003',
                'latitude' => 41.1098,
                'longitude' => 1.2492,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tour por el Museo del Prado',
                'description' => 'Descubre una de las colecciones de arte más importantes del mundo, con obras de maestros como Velázquez, Goya y El Greco.',
                'photo' => 'museo_del_prado.jpg',
                'type' => 'Museos',
                'place_id' => 5,
                'price' => 20.00,
                'address' => 'Paseo del Prado, s/n, 28014',
                'latitude' => 40.4139,
                'longitude' => -3.6925,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recorrido por la Catedral de Toledo',
                'description' => 'Admira la arquitectura gótica de esta impresionante catedral, que alberga obras de arte de El Greco.',
                'photo' => 'catedral_toledo.jpg',
                'type' => 'Monumentos',
                'place_id' => 6,
                'price' => 10.00,
                'address' => 'Calle Cardenal Cisneros, 1, 45002',
                'latitude' => 39.8574,
                'longitude' => -4.0237,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exploración del Casco Antiguo de Oviedo',
                'description' => 'Sumérgete en la historia y la cultura de Asturias mientras paseas por las calles empedradas y descubres edificios históricos.',
                'photo' => 'casco_antiguo_oviedo.jpg',
                'type' => 'Turismo',
                'place_id' => 7,
                'price' => 8.00,
                'address' => 'Casco Antiguo',
                'latitude' => 43.3614,
                'longitude' => -5.8456,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Visita al Alcázar de Segovia',
                'description' => 'Contempla el imponente castillo que inspiró el diseño del castillo de Disney y disfruta de las vistas panorámicas de la ciudad.',
                'photo' => 'alcazar_segovia.jpg',
                'type' => 'Monumentos',
                'place_id' => 8,
                'price' => 12.00,
                'address' => 'Plaza Reina Victoria Eugenia, s/n, 40003 Segovia, España',
                'latitude' => 40.9485,
                'longitude' => -4.1179,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ruta por el Conjunto Monumental de Lorca',
                'description' => 'Descubre la riqueza histórica y arquitectónica de Lorca explorando sus monumentos, como el Castillo de Lorca y la Colegiata de San Patricio.',
                'photo' => 'conjunto_monumental_lorca.jpg',
                'type' => 'Turismo',
                'place_id' => 9,
                'price' => 7.50,
                'address' => 'Castillo de Lorca, s/n, 30800 Lorca, Murcia, España',
                'latitude' => 37.6695,
                'longitude' => -1.6966,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caminata por la Ciudad Encantada',
                'description' => 'Maravíllate con las formaciones rocosas únicas de este paraje natural, que parecen esculpidas por la mano de un artista.',
                'photo' => 'ciudad_encantada_cuenca.jpg',
                'type' => 'Turismo',
                'place_id' => 10,
                'price' => 5.00,
                'address' => 'CM-2105, 16146 Valdecabras, Cuenca, España',
                'latitude' => 40.1308,
                'longitude' => -2.1191,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Visita a la Catedral de Chartres',
                'description' => 'Explora esta impresionante catedral gótica, famosa por sus vidrieras medievales y su laberinto tallado en el suelo.',
                'photo' => 'catedral_chartres.jpg',
                'type' => 'Monumentos',
                'place_id' => 11,
                'price' => 10.00,
                'address' => '16 Cloître Notre-Dame, 28000 Chartres, Francia',
                'latitude' => 48.4474,
                'longitude' => 1.4871,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Degustación de vinos en Arpino',
                'description' => 'Descubre los sabores de la región de Lazio con una cata de vinos en una bodega local en Arpino.',
                'photo' => 'degustacion_vinos_arpino.jpg',
                'type' => 'Gastronomía',
                'place_id' => 12,
                'price' => 20.00,
                'address' => 'Via Fontana, 14, 03034 Arpino FR, Italia',
                'latitude' => 41.6341,
                'longitude' => 13.6202,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recorrido por el Castillo de Neuschwanstein',
                'description' => 'Visita el icónico castillo de cuento de hadas de Baviera, construido por el Rey Luis II.',
                'photo' => 'castillo_neuschwanstein_fussen.jpg',
                'type' => 'Turismo',
                'place_id' => 13,
                'price' => 15.00,
                'address' => 'Neuschwansteinstraße 20, 87645 Schwangau, Alemania',
                'latitude' => 47.5576,
                'longitude' => 10.7498,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
