<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hotels')->insert([
            [
                'name' => 'AC Hotel Almería by Marriott',
                'description' => 'Este hotel elegante se encuentra en el centro de Almería, a pocos pasos de la Plaza de las Flores.',
                'photo' => 'acalmeria.jpg',
                'services' => 'Wifi gratuito, restaurante, bar, gimnasio',
                'classification' => 4,
                'address' => 'Plaza Flores, 5, 04001',
                'latitude' => 36.8403,
                'longitude' => -2.4659,
                'place_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NH Collection Granada Victoria',
                'description' => 'Un hotel moderno ubicado en el centro de Granada.',
                'photo' => 'nhgranada.jpg',
                'services' => 'Wi-Fi, restaurante, bar, parking',
                'classification' => 4,
                'address' => 'Puerta Real, 3, 18005',
                'latitude' => 37.1759,
                'longitude' => -3.5986,
                'place_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hotel Arts Barcelona',
                'description' => 'Un lujoso hotel con vistas al mar en Barcelona.',
                'photo' => 'artsbcn.jpg',
                'services' => 'Wi-Fi, piscina, spa, restaurante',
                'classification' => 5,
                'address' => 'Carrer de la Marina, 19-21, 08005',
                'latitude' => 41.3890,
                'longitude' => 2.1931,
                'place_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AC Hotel Tarragona by Marriott',
                'description' => 'Un moderno hotel cerca del centro histórico de Tarragona.',
                'photo' => 'actgn.jpg',
                'services' => 'Wi-Fi, gimnasio, bar, parking',
                'classification' => 4,
                'address' => 'Carrer de Mallorca, 52, 43001',
                'latitude' => 41.1196,
                'longitude' => 1.2455,
                'place_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Westin Palace, Madrid',
                'description' => 'Un hotel icónico en el corazón de Madrid.',
                'photo' => 'westinmdd.jpg',
                'services' => 'Wi-Fi, piscina, spa, restaurante',
                'classification' => 5,
                'address' => 'Plaza de las Cortes, 7, 28014',
                'latitude' => 40.4150,
                'longitude' => -3.6973,
                'place_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eurostars Toledo',
                'description' => 'Un hotel con encanto en el casco antiguo de Toledo.',
                'photo' => 'eurostar.jpg',
                'services' => 'Wi-Fi, restaurante, bar',
                'classification' => 4,
                'address' => 'Paseo de San Eugenio, s/n, 45003',
                'latitude' => 39.8564,
                'longitude' => -4.0258,
                'place_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Barceló Oviedo Cervantes',
                'description' => 'Un hotel elegante en el centro de Oviedo.',
                'photo' => 'barcel.jpg',
                'services' => 'Wi-Fi, gimnasio, bar, parking',
                'classification' => 5,
                'address' => 'C/ Cervantes, 13, 33004',
                'latitude' => 43.3634,
                'longitude' => -5.8460,
                'place_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hotel Infanta Isabel',
                'description' => 'Un hotel histórico en la Plaza Mayor de Segovia.',
                'photo' => 'isabel.jpg',
                'services' => 'Wi-Fi, restaurante, bar',
                'classification' => 3,
                'address' => 'Plaza Mayor 12, 40001',
                'latitude' => 40.9495,
                'longitude' => -4.1246,
                'place_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Parador de Lorca',
                'description' => 'Un parador histórico ubicado en el Castillo de Lorca.',
                'photo' => 'parador.jpg',
                'services' => 'Wi-Fi, restaurante, bar, piscina',
                'classification' => 4,
                'address' => 'Castillo de Lorca, s/n, 30800',
                'latitude' => 37.6695,
                'longitude' => -1.6966,
                'place_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Parador de Cuenca',
                'description' => 'Un parador con vistas espectaculares en Cuenca.',
                'photo' => 'paradorcuenca.jpg',
                'services' => 'Wi-Fi, restaurante, bar, spa',
                'classification' => 4,
                'address' => 'Cerro del Socorro, s/n, 16001',
                'latitude' => 40.0721,
                'longitude' => -2.1408,
                'place_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Best Western Premier Grand Monarque Hotel & Spa',
                'description' => 'Un hotel con encanto en el centro de Chartres.',
                'photo' => 'Chartres.jpg',
                'services' => 'Wi-Fi, restaurante, bar, spa',
                'classification' => 4,
                'address' => '22 Place des Epars, 28000 Chartres, Francia',
                'latitude' => 48.4473,
                'longitude' => 1.4844,
                'place_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hotel Il Cavalier D\Arpino',
                'description' => 'Un acogedor hotel en el corazón de Arpino.',
                'photo' => 'cavalier.jpg',
                'services' => 'Wi-Fi, restaurante, bar',
                'classification' => 3,
                'address' => 'Piazza Municipio 2, 03033',
                'latitude' => 41.7003,
                'longitude' => 13.6258,
                'place_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hotel Schlosskrone',
                'description' => 'El Hotel Schlosskrone ofrece habitaciones elegantes.',
                'photo' => 'schlosskrone.jpg',
                'services' => 'Wi-Fi, desayuno buffet, restaurante, bar, spa',
                'classification' => 4,
                'address' => 'Prinzregentenplatz 4, 87629',
                'latitude' => 47.5697,
                'longitude' => 10.6935,
                'place_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
